# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install tox codecov

# command to run tests using coverage, e.g. python setup.py test
script:
    - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}

after_success:
  - codecov
